openapi: 3.0.3

info:
  version: 2.0.0-beta.1
  title: sync.muilab.org
  description: api spec for SYNC frontend SPA

servers:
  - url: "https://sync.muilab.org/api/v2"

paths:
  /articles/homepage:
    $ref: "paths/article/Homepage.yaml"
  /articles/{articleId}:
    $ref: "paths/article/ArticleId.yaml"
  /articles/create:
    $ref: "paths/article/Create.yaml"
  /articles:
    $ref: "paths/article/Tag.yaml"
  /user/auth:
    $ref: "paths/user/auth.yaml"
# components:
#   # TODO: security schemes
#   securitySchemes:
