name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Format
        run: |
          yarn format:check | \
            xargs -I {} echo "::error file={}::Format needed, run 'yarn format' to fix it"
      - name: Lint
        run: yarn lint:check | echo
